tasks:
  - before: >
        mkdir -p ~/.ssh &&
        [[ ! -z $GP_SSH_SIGNING_KEY  ]] &&
        echo $GP_SSH_SIGNING_KEY > ~/.ssh/id_rsa.pub &&
        chmod 644 ~/.ssh/id_rsa.pub &&
        [[ ! -z $GP_SSH_SIGNING_PRIVKEY  ]] &&
        echo $GP_SSH_SIGNING_PRIVKEY | base64 -d > ~/.ssh/id_rsa &&
        chmod 600 ~/.ssh/id_rsa
  - name: Git config for signing commits
    init: git config --global gpg.format ssh && git config --global user.signingkey /home/gitpod/.ssh/id_rsa.pub && git config --global commit.gpgsign true
    command: bash

vscode:
    extensions:
        - marp-team.marp-vscode
        - ms-python.python
        - mhutchie.git-graph
        - ritwickdey.LiveServer
